var searchData=
[
  ['salesfloorstaff_0',['SalesFloorStaff',['../class_sales_floor_staff.html',1,'']]],
  ['sample_20session_1',['Sample Session',['../md__c_u_s_t_o_m_e_r___o_r_d_e_r___t_e_s_t___r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['sendresponse_2',['sendResponse',['../class_network_server.html#a2be5835e8720f3e7fce1d6d78c84714b',1,'NetworkServer']]],
  ['separate_20terminal_3',['Step 2: Start Java GUI (in a separate terminal)',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md47',1,'']]],
  ['session_4',['Sample Session',['../md__c_u_s_t_o_m_e_r___o_r_d_e_r___t_e_s_t___r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['setbuilder_5',['setBuilder',['../class_order_director.html#af12aecb104e0bf2d0cfe618d73ddeabc',1,'OrderDirector']]],
  ['setbusy_6',['setBusy',['../class_staff_chain_handler.html#a24e6f4383bc838f809028dfc4a413858',1,'StaffChainHandler']]],
  ['setbusyfor_7',['setBusyFor',['../class_staff_chain_handler.html#af97a97611037f5f552dad85fcc2e1ba5',1,'StaffChainHandler']]],
  ['setdiscount_8',['setDiscount',['../class_plant_bundle.html#a10dda8a8fc01e883e28fcc0333d197db',1,'PlantBundle']]],
  ['setmanager_9',['setManager',['../class_staff_chain_handler.html#ae96e1aa65e1797fb6389e1f698b6768b',1,'StaffChainHandler']]],
  ['setnext_10',['setNext',['../class_staff_chain_handler.html#a9f9f37d0f5fda2056fca98ca76041340',1,'StaffChainHandler']]],
  ['setobserver_11',['setObserver',['../class_plant_product.html#a089b8d1d906d7fef5752772a7dc61cd3',1,'PlantProduct']]],
  ['setorderdate_12',['setOrderDate',['../class_order.html#adc6acf0a3727f600653b23ac2ebe78d0',1,'Order']]],
  ['setstatus_13',['setStatus',['../class_order.html#a0c0d356d8305b1874bf1c4d39d750e73',1,'Order']]],
  ['setup_20user_20guide_14',['Greenhouse Management System - Setup &amp;amp; User Guide',['../md__s_e_t_u_p___g_u_i_d_e.html',1,'']]],
  ['simulation_20mode_15',['Mode 2: Console Simulation Mode',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md50',1,'']]],
  ['single_20plant_20to_20order_16',['2. Add Single Plant to Order',['../md__c_u_s_t_o_m_e_r___o_r_d_e_r___t_e_s_t___r_e_a_d_m_e.html#autotoc_md11',1,'']]],
  ['singleplant_17',['SinglePlant',['../class_single_plant.html',1,'']]],
  ['software_18',['Software',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md32',1,'']]],
  ['staffchainhandler_19',['StaffChainHandler',['../class_staff_chain_handler.html',1,'']]],
  ['staffcontext_20',['StaffContext',['../struct_staff_context.html',1,'']]],
  ['staffmanager_21',['StaffManager',['../class_staff_manager.html',1,'']]],
  ['staffmanager_2ecpp_22',['StaffManager.cpp',['../_staff_manager_8cpp.html',1,'']]],
  ['staffmember_23',['StaffMember',['../class_staff_member.html',1,'']]],
  ['staffmember_2ecpp_24',['StaffMember.cpp',['../_staff_member_8cpp.html',1,'']]],
  ['standardpruningstrategy_25',['StandardPruningStrategy',['../class_standard_pruning_strategy.html',1,'']]],
  ['start_26',['start',['../class_network_server.html#a1b27694d6823cac0a20b62ae7d809f21',1,'NetworkServer']]],
  ['start_20c_20backend_27',['Step 1: Start C++ Backend',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md46',1,'']]],
  ['start_20java_20gui_20in_20a_20separate_20terminal_28',['Step 2: Start Java GUI (in a separate terminal)',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md47',1,'']]],
  ['status_29',['Monitoring System Status',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md56',1,'']]],
  ['step_201_3a_20start_20c_20backend_30',['Step 1: Start C++ Backend',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md46',1,'']]],
  ['step_202_3a_20start_20java_20gui_20in_20a_20separate_20terminal_31',['Step 2: Start Java GUI (in a separate terminal)',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md47',1,'']]],
  ['step_203_3a_20use_20the_20system_32',['Step 3: Use the System',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md48',1,'']]],
  ['steps_33',['Next Steps',['../md__c_u_s_t_o_m_e_r___o_r_d_e_r___t_e_s_t___r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['stop_34',['stop',['../class_network_server.html#af925de906d78b27e43e72f3a22b63fce',1,'NetworkServer']]],
  ['structure_35',['3. Verify Project Structure',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md38',1,'']]],
  ['structure_20reference_36',['File Structure Reference',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md72',1,'']]],
  ['submit_20order_20for_20validation_37',['5. Submit Order for Validation',['../md__c_u_s_t_o_m_e_r___o_r_d_e_r___t_e_s_t___r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['succulentprofile_38',['SucculentProfile',['../class_succulent_profile.html',1,'']]],
  ['system_39',['System',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md44',1,'Running the System'],['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md48',1,'Step 3: Use the System']]],
  ['system_20capacity_40',['System Capacity',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md68',1,'']]],
  ['system_20components_41',['System Components',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md59',1,'']]],
  ['system_20requirements_42',['System Requirements',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md30',1,'']]],
  ['system_20setup_20user_20guide_43',['Greenhouse Management System - Setup &amp;amp; User Guide',['../md__s_e_t_u_p___g_u_i_d_e.html',1,'']]],
  ['system_20status_44',['Monitoring System Status',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md56',1,'']]]
];
