var searchData=
[
  ['parameters_0',['Timing Parameters',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md69',1,'']]],
  ['patterns_1',['Patterns',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md58',1,'Architecture &amp; Design Patterns'],['../md__c_u_s_t_o_m_e_r___o_r_d_e_r___t_e_s_t___r_e_a_d_m_e.html#autotoc_md3',1,'Design Patterns']]],
  ['patterns_20demonstrated_3a_2',['Design Patterns Demonstrated:',['../C:/Users/ssibi/Documents/School/2025/Semester 2/COS 214/FinalProject/COS214-P5/main.cpp#autotoc_md24',1,'']]],
  ['patterns_20used_3',['Design Patterns Used',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md60',1,'']]],
  ['paymentprocesshandler_4',['PaymentProcessHandler',['../class_payment_process_handler.html',1,'']]],
  ['paymentprocessor_5',['PaymentProcessor',['../class_payment_processor.html',1,'']]],
  ['performance_20notes_6',['Performance Notes',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md67',1,'']]],
  ['performcare_7',['performCare',['../class_plant_product.html#af25b4492d3f546e6b1ea20b5803f79f3',1,'PlantProduct']]],
  ['placeordercommand_8',['PlaceOrderCommand',['../class_place_order_command.html',1,'']]],
  ['plant_20bundle_20to_20order_9',['3. Add Plant Bundle to Order',['../md__c_u_s_t_o_m_e_r___o_r_d_e_r___t_e_s_t___r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['plant_20to_20order_10',['2. Add Single Plant to Order',['../md__c_u_s_t_o_m_e_r___o_r_d_e_r___t_e_s_t___r_e_a_d_m_e.html#autotoc_md11',1,'']]],
  ['plantbundle_11',['PlantBundle',['../class_plant_bundle.html',1,'PlantBundle'],['../class_plant_bundle.html#a3ea34591787d1ec3612546182788ff15',1,'PlantBundle::PlantBundle()']]],
  ['plantdata_12',['PlantData',['../class_plant_data.html',1,'']]],
  ['plantedstate_13',['PlantedState',['../class_planted_state.html',1,'']]],
  ['plantgroup_14',['PlantGroup',['../class_plant_group.html',1,'']]],
  ['plantpot_15',['PlantPot',['../class_plant_pot.html',1,'PlantPot'],['../class_plant_pot.html#aa5648560fa0c1b2954ebf8c1f8c5f993',1,'PlantPot::PlantPot()']]],
  ['plantproduct_16',['PlantProduct',['../class_plant_product.html',1,'PlantProduct'],['../class_plant_product.html#afadafde1f8fd81945e2ea00e0d0de69c',1,'PlantProduct::PlantProduct()']]],
  ['plantproductleaf_17',['PlantProductLeaf',['../class_plant_product_leaf.html',1,'PlantProductLeaf'],['../class_plant_product_leaf.html#a4ae18926a68024573f675ddf654f008b',1,'PlantProductLeaf::PlantProductLeaf()']]],
  ['plants_18',['1. View Available Plants',['../md__c_u_s_t_o_m_e_r___o_r_d_e_r___t_e_s_t___r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['plants_20via_20gui_19',['Adding Plants via GUI',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md53',1,'']]],
  ['plantspeciesprofile_20',['PlantSpeciesProfile',['../class_plant_species_profile.html',1,'']]],
  ['plantstate_21',['PlantState',['../class_plant_state.html',1,'']]],
  ['plasticpot_22',['PlasticPot',['../class_plastic_pot.html',1,'PlasticPot'],['../class_plastic_pot.html#ada9c1ff7d76845af2ade5a2d1de30f4b',1,'PlasticPot::PlasticPot()']]],
  ['plasticpotfactory_23',['PlasticPotFactory',['../class_plastic_pot_factory.html',1,'']]],
  ['pot_24',['Pot',['../class_pot.html',1,'Pot'],['../class_pot.html#a46a8f96ed4f950e471b11ed01298da10',1,'Pot::Pot()']]],
  ['potfactory_25',['PotFactory',['../class_pot_factory.html',1,'']]],
  ['processing_20customer_20orders_26',['Processing Customer Orders',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md55',1,'']]],
  ['processpayment_27',['processPayment',['../class_cash_adapter.html#af3b0f6610529e28080f7d06a3f6724ce',1,'CashAdapter::processPayment()'],['../class_credit_card_adapter.html#a22cd52cc1262e00c508e38d600c41a03',1,'CreditCardAdapter::processPayment()'],['../class_e_f_t_adapter.html#a6b60efeaceb71a0a0b3b3c59549072c2',1,'EFTAdapter::processPayment()']]],
  ['project_28',['Building the Project',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md40',1,'']]],
  ['project_20files_29',['2. Clone/Copy Project Files',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md37',1,'']]],
  ['project_20structure_30',['3. Verify Project Structure',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md38',1,'']]],
  ['protocol_20reference_31',['Command Protocol Reference',['../md__s_e_t_u_p___g_u_i_d_e.html#autotoc_md73',1,'']]],
  ['prunecommand_32',['PruneCommand',['../class_prune_command.html',1,'']]]
];
